version: "3.8"

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=flaskr
      - FLASK_RUN_HOST=0.0.0.0
    command: ["flask", "--app", "flaskr", "run", "--host=0.0.0.0"]
